### PR TITLE
fix: update LDF.collect() for polars==0.19.8

### PR DESCRIPTION
**Pull request by brendancooley**
`polars` removed **kwargs from [`LazyFrame.collect()`](https://github.com/pola-rs/polars/blob/d42e05903792d30c11fa16e496b88a77bd227bae/py-polars/polars/lazyframe/frame.py#L1657) in the 0.19.8 [release](https://github.com/pola-rs/polars/releases/tag/py-0.19.8). Since the signature for `patito`'s child `LDF.collect` does not match that of `pl.LazyFrame.collect`, the `test_dummy_data` suite fails after upgrading `polars`. This PR moves `collect` to an `*args, **kwargs` pattern for better backward/forward compatibility. Tests pass with `polars==0.19.8` and `polars==0.18.7`.

### CODE REVIEW

**Comment by ion-elgreco** [comment]
Thanks I also ran into the issue, I've merged this fix into my own develop branch of patito fork. There isn't much activity in this repo anymore it seems.

**Comment by thomasaarholt** [comment]
We're working on a migration to pydantic v2, it's just difficult to squeeze in development time between our jobs.

**Comment by ion-elgreco** [comment]
> We're working on a migration to pydantic v2, it's just difficult to squeeze in development time between our jobs.

Wouldn't it then make sense to at least merge all the fixes, so the current release works as expected?

**Comment by thomasaarholt** [comment]
We have a work-in-progress branch that we are migrating the pydantic work with, and it is extensive enough that we didn't want to risk having to do rebases while still doing that. I agree that the fixes here are valuable, but we decided to prioritize the pydantic migration first.

**Comment by ion-elgreco** [comment]
> We have a work-in-progress branch that we are migrating the pydantic work with, and it is extensive enough that we didn't want to risk having to do rebases while still doing that. I agree that the fixes here are valuable, but we decided to prioritize the pydantic migration first.

Are all the current issues accounted for in the Pydantic v2 release or will the same issues persist?

**Comment by thomasaarholt** [comment]
We will likely have fixed some issues, while others will persist. We will rebase the PRs on the pydantic-migrated-version and then go through the PRs one by one.

**Comment by ion-elgreco** [comment]
> We will likely have fixed some issues, while others will persist. We will rebase the PRs on the pydantic-migrated-version and then go through the PRs one by one.

If you need any help to port the fixes to the pydantic-migrated version, I am happy to help there. We use Patito quite extensively in our codebase

**Comment by thomasaarholt** [comment]
This is now fixed in the main branch :)

**Pull request closed without merging**
